# Change baseurl before deploy
baseurl = "https://FlowerCA77.github.io"
languageCode = "zh-cn"
title = "CA77"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

enableRobotsTXT = true

colorScheme = "light"
default = "light"
toggle = false

[pagination]
pagerSize = 5
